//! Speck-128/256 Block Cipher Implementation
//!
//! **File:** `speck.rs`
//! **Author:** Kevin Thomas
//! **Date:** 2026
//!
//! MIT License
//!
//! Copyright (c) 2026 Kevin Thomas
//!
//! Permission is hereby granted, free of charge, to any person obtaining a copy
//! of this software and associated documentation files (the "Software"), to deal
//! in the Software without restriction, including without limitation the rights
//! to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//! copies of the Software, and to permit persons to whom the Software is
//! furnished to do so, subject to the following conditions:
//!
//! The above copyright notice and this permission notice shall be included in
//! all copies or substantial portions of the Software.
//!
//! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//! FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//! AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//! LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//! OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//! SOFTWARE.

/// Number of rounds in the Speck-128/256 key schedule.
const ROUNDS: usize = 34;

#[must_use]
/// Expands a 256-bit Speck key into its 34 round keys.
///
/// # Arguments
///
/// * `key` - Four 64-bit key words in little-endian order.
///
/// # Returns
///
/// The round-key schedule used by `encrypt_block`.
pub fn expand_key(key: &[u64; 4]) -> [u64; ROUNDS] {
    let (mut keys, mut l) = ([0u64; ROUNDS], [key[1], key[2], key[3]]);
    keys[0] = key[0];
    for i in 0..(ROUNDS - 1) {
        (l[i % 3], keys[i + 1]) = next_round_key(l[i % 3], keys[i], i as u64);
    }
    keys
}

/// Applies a single Speck round function during key expansion.
///
/// # Arguments
///
/// * `l` - Current auxiliary schedule word.
/// * `k` - Current round key word.
/// * `i` - Round index mixed into the schedule.
///
/// # Returns
///
/// The next auxiliary word and next round key word.
fn next_round_key(l: u64, k: u64, i: u64) -> (u64, u64) {
    let l_next = l.rotate_right(8).wrapping_add(k) ^ i;
    let k_next = k.rotate_left(3) ^ l_next;
    (l_next, k_next)
}

/// Encrypts a single 128-bit block in-place using Speck-256.
///
/// # Arguments
///
/// * `block` - Two 64-bit words representing the plaintext block.
/// * `round_keys` - Expanded key schedule generated by `expand_key`.
///
/// # Returns
///
/// This function does not return a value; it mutates `block` in place.
pub fn encrypt_block(block: &mut [u64; 2], round_keys: &[u64; ROUNDS]) {
    let (mut x, mut y) = (block[0], block[1]);
    for &k in round_keys {
        x = x.rotate_right(8).wrapping_add(y) ^ k;
        y = y.rotate_left(3) ^ x;
    }
    *block = [x, y];
}

#[cfg(test)]
mod tests {
    // Import all parent module items
    use super::*;

    /// Verifies the Speck-128/256 reference test vector.
    #[test]
    fn test_speck_128_256() {
        let key = [
            0x0706_0504_0302_0100,
            0x0f0e_0d0c_0b0a_0908,
            0x1716_1514_1312_1110,
            0x1f1e_1d1c_1b1a_1918,
        ];
        let mut block = [0x6573_6f68_7420_6e49, 0x202e_7265_6e6f_6f70];
        let round_keys = expand_key(&key);
        encrypt_block(&mut block, &round_keys);
        assert_eq!(block, [0x4109_0104_05c0_f53e, 0x4eee_b48d_9c18_8f43]);
    }
}
